name: SANE
version: 78f3160
slug: sane-scanner
description: A SANE server for wireless scanning
url: https://github.com/joschi-ha/addon-sane
arch:
- amd64
- aarch64
- armhf
- armv7
- i386
usb: true
init: false
homeassistant_api: true
host_network: true
map:
- addon_config:rw
image: ghcr.io/joschi-ha/sane-scanner/{arch}
